### ISSUE TITLE
Ruby 2.0.0dev VMC_HTTP_ERROR_CODES HTTP_TIMEOUT error

### ISSUE THREAD

**Issue by igmarin** [appfog/af#21]
Using Ruby 2.0 i got the following errors:

ruby-2.0.0-preview1/gems/af-0.3.18.10/lib/vmc/client.rb:28: warning: already initialized constant VMC_HTTP_ERROR_CODES

ruby-2.0.0-preview1/gems/af-0.3.18.10/lib/vmc/client.rb:28: warning: previous definition of VMC_HTTP_ERROR_CODES was here

ruby-2.0.0-preview1/gems/af-0.3.18.10/lib/vmc/client.rb:30: warning: already initialized constant HTTP_TIMEOUT

ruby-2.0.0-preview1/gems/af-0.3.18.10/lib/vmc/client.rb:30: warning: previous definition of HTTP_TIMEOUT was here

**Comment by khhuff** [comment]
At this time AppFog does not support ruby version 2.0. To log-in and interact from the cli you will need to use Ruby 1.9.3 or lower. Thanks
