### ISSUE TITLE
Azure available as an infra

### ISSUE THREAD

**Issue by patcon** [appfog/af#24]
New to AppFog, but wondering what the blockers might be to making some Azure datacentres available through the `--infra` flag? Is Azure already accessible through the API and it's simply a matter of contributing some improvements to the gem? And if it's more than that, any idea about an ETA on that?

**Comment by khhuff** [comment]
patcon

We currently do not support Azure, that may change in the future with the release of AppFog v2. Keep on the lookout via our blog: http://blog.appfog.com/

**Comment by patcon** [comment]
As a data point, I'm no longer interested in working with Azure. Just fyi so I don't go onto a +1 list :)
