### ISSUE TITLE
"Bad file number" after logging in on Solaris

### ISSUE THREAD

**Issue by wh0** [appfog/af#30]
https://github.com/appfog/af/blob/957104a87df1911ade0d2a11cf877d4a72a52106/lib/cli/config.rb#L145

This line fails on Solaris, which does not allow exclusive locks on files opened as read only.

Is there a reason for obtaining an exclusive lock on a file opened for reading only?

**Comment by khhuff** [comment]
If you still have any issues, please submit a support request at support@appfog.com. Thanks.
