### ISSUE TITLE
af manifest producing incorrect 'manifest.yml'

### ISSUE THREAD

**Issue by malthejorgensen** [appfog/af#44]
When I run `af manifest` I get an incorrect `manifest.yml` file.

Sample run:

    $ af manifest
    Configure for which application? [.]: .
    Detected a Python Django Application, is this correct? [Yn]: 
    1: AWS US East - Virginia
    2: AWS EU West - Ireland
    3: AWS Asia SE - Singapore
    4: HP AZ 2 - Las Vegas
    Select Infrastructure: 2
    Application Deployed URL [lektieproblemer.eu01.aws.af.cm]: 
    Memory reservation (128M, 256M, 512M, 1G, 2G) [128M]: 
    How many instances? [1]: 
    Bind existing services to 'lektieproblemer'? [yN]: y
    1: lektieproblemer-mysql-19350
    Which one?: 1
    Create services to bind to 'lektieproblemer'? [yN]: 
    Configure for another application? [yN]: 
    Manifest written to manifest.yml.

Writes the following `manifest.yml`:

    ---
    name: lektieproblemer
    applications:
      .:
        framework:
          name: django
          info:
            mem: 128M
            description: Python Django Application
            exec: 
        infra: eu-aws
        url: ${name}.${target-base}
        mem: 128M
        instances: 1
        services:
          lektieproblemer-mysql-19350:
            type: mysql

Which, to my understanding, is not correct.
Running `af update` will not work, for example:

    $ af update
    Updating application ''...
    can't convert Symbol into Integer
    [stacktrace omitted]

**Comment by khhuff** [comment]
If you still have any issues, please submit a ticket to support@appfog.com. Thanks
