### ISSUE TITLE
Remove Erlang/OTP rebar from application type list

### ISSUE THREAD

**Issue by edgurgel** [appfog/af#45]
The following application type list shows up when I'm using af: 
```
Detected a Standalone Application, is this correct? [Yn]: n
1: Rails
2: Spring
3: Grails
4: Lift
5: JavaWeb
6: Standalone
7: Sinatra
8: Node
9: PHP
10: Erlang/OTP Rebar
11: WSGI
12: Django
13: Rack
14: Play
```

But it seems like there's no support to Erlang/OTP Rebar. Is it correct?

**Comment by khhuff** [comment]
Correct, at this time we do not support Erlang/OTP Rebar. This may be achieved with AppFog v2 when it is ready to be released. Stay tuned to http://blog.appfog.com/ for more news. Thanks.
