### ISSUE TITLE
error when execute 'af login'

### ISSUE THREAD

**Issue by xuxiang** [appfog/af#47]
Error:
[0m[31mnon-absolute home[0m
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/config.rb:89:in `expand
_path'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/config.rb:89:in `aliase
s'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/runner.rb:467:in `proce
ss_aliases!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/runner.rb:501:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/runner.rb:14:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/bin/af:5:in `<top (required)>'
C:/Ruby193/bin/af:23:in `load'
C:/Ruby193/bin/af:23:in `< main >'

**Comment by khhuff** [comment]
If you are still having a login issue, please submit a ticket to support@appfog.com Thanks.
