### ISSUE TITLE
AF Login Error

### ISSUE THREAD

**Issue by cooolbasha** [appfog/af#49]
Hi, 
when I enter AF Login it throws error
can't convert Symbol into Integer 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/vmc/client.rb:380:in `[]' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/vmc/client.rb:380:in `block in base_for_infra' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/vmc/client.rb:380:in `each' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/vmc/client.rb:380:in `detect' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/vmc/client.rb:380:in `base_for_infra' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/vmc/client.rb:408:in `suggest_url' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:182:in `target_base' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:125:in `resolve_symbol' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:115:in `block in resolve_lexically' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:114:in `gsub!' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:114:in `resolve_lexically' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:107:in `block in resolve_lexically' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:106:in `each_value' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:106:in `resolve_lexically' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:74:in `block in resolve_manifest' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:73:in `each_value' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:73:in `resolve_manifest' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:83:in `load_manifest' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/commands/base.rb:28:in `initialize' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/runner.rb:506:in `new' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/runner.rb:506:in `run' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/lib/cli/runner.rb:14:in `run' 
C:/Ruby193/lib/ruby/gems/1.9.1/gems/af-0.3.18.12/bin/af:5:in `<top (required)>' 
C:/Ruby193/bin/af:23:in `load' 
C:/Ruby193/bin/af:23:in `<main>'

**Comment by khhuff** [comment]
cooolbasha,

Try uninstalling then re-installing your ruby version. We have since updated our af gem as well. If you still require log-in assistance please submit a ticket to support@appfog.com. Thanks.
